[program:reductstore]
process_name=%(program_name)s
priority=10
environment=RS_DATA_PATH="/home/rpi4/reduct-media"
directory=/home/rpi4/reduct-media
command=/home/rpi4/.cargo/bin/reductstore
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
