[group:test_tube]
programs=webUI,planification,services

[program:webUI]
process_name=%(program_name)s
priority=500
directory=/home/rpi4/PlanarianScanner/test_tube_scanner
command=
    /home/rpi4/PlanarianScanner/.venv/bin/daphne
    -b 0.0.0.0
    -p 8000
    home.asgi:application
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

[program:planification]
process_name=%(program_name)s
priority=800
directory=/home/rpi4/PlanarianScanner/test_tube_scanner
command=/home/rpi4/PlanarianScanner/.venv/bin/celery -A home beat -l info
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

[program:services]
process_name=%(program_name)s
priority=900
directory=/home/rpi4/PlanarianScanner/test_tube_scanner
command=/home/rpi4/PlanarianScanner/test_tube_scanner/run-workers.sh
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

