[group:test_tube]
programs=scanner,beat,workers

[program:scanner]
process_name=%(program_name)s
priority=500
directory=/home/rpi4/django-test-tube-scanner/test_tube_scanner
command=
    /home/rpi4/django-test-tube-scanner/.venv/bin/daphne
    -b 0.0.0.0
    -p 8000
    home.asgi:application
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

[program:beat]
process_name=%(program_name)s
priority=800
directory=/home/rpi4/django-test-tube-scanner/test_tube_scanner
command=/home/rpi4/django-test-tube-scanner/.venv/bin/celery -A home beat -l info
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

[program:workers]
process_name=%(program_name)s
priority=900
directory=/home/rpi4/django-test-tube-scanner/test_tube_scanner
command=/home/rpi4/django-test-tube-scanner/run-workers.sh
user=rpi4
group=rpi4
stopasgroup=true
stopsignal=SIGINT
autostart=true
autorestart=true
redirect_stderr=true

